### PR TITLE
fix stadtforum embedding on old mein.berlin.de

### LINKED ISSUE #2231: old mein.berlin.de: Stadtforum embedding is broken
When I navigate to mein.berlin.de and click on a Stadtforum process (e.g. https://www.berlin.de/familie/umfrage), I get a broken (i.e. I can't post comments or rates) embedded process and the error message:

> GET https://mein.berlin.de/apil_0000000/VERSION_0000001 404 (Not Found)

while the URL that should have been accessed is:

> https://mein.berlin.de/api/familienportal/dialog/poll_0000000/VERSION_0000001/

So a part of the path is swallowed by the frontend routing.

### PR DESCRIPTION
**Pull request by Johnschmidfront**
this should fix #2231.

I couldn't test it, unfortunately, because I could never reproduce the error in the issue locally.

But I think I found the problem:

In `ResourceArea.ts`, the function `getProcess` assumed that its input string `resourceUrl` was a complete URL, not a relative path, and then chopped it accordingly.

### CODE REVIEW

**Comment by 2e2a** [comment]
LGTM.

File: src/adhocracy_frontend/adhocracy_frontend/static/js/Packages/ResourceArea/ResourceArea.ts [hunk 1]
```diff
@@ -242,7 +242,12 @@ export class Service implements AdhTopLevelState.IAreaInput {
     public getProcess(resourceUrl : string, fail = true) : angular.IPromise<ResourcesBase.Resource> {
         var paths = [];
 
-        var path = resourceUrl.substr(this.adhConfig.rest_url.length);
+        // FIXME: This if-Statement was added for the special case that resourceUrl is a URL,
+        // not a relative path. It should be erased when the archived Stadtforum processes go offline.
+        if (resourceUrl.substr(0, 4) === "http") {
+            var path = resourceUrl.substr(this.adhConfig.rest_url.length);
+        }
```
Comment (xi) [inline src/adhocracy_frontend/adhocracy_frontend/static/js/Packages/ResourceArea/ResourceArea.ts]: `path` is `undefined` if this block is not executed.

Comment (Johnschmidfront) [inline src/adhocracy_frontend/adhocracy_frontend/static/js/Packages/ResourceArea/ResourceArea.ts]: omg. horrible mistake.
