### PR TITLE
fix Alexanderplatz proposals

### LINKED ISSUE #2543: No proposals are shown in the Alexanderplatz process
https://mein.berlin.de/w/prozesse/workshopverfahren-2015/#!r/alexanderplatz/workshopverfahren-2015/@proposals

### PR DESCRIPTION
**Pull request by der-john**
Fixes #2543.

### CODE REVIEW

**Comment by xi** [comment]
The proposals still do not show on the map. Apart from that it looks fine.

File: src/meinberlin/meinberlin/static/js/Packages/Meinberlin/Alexanderplatz/Workbench/Module.ts [hunk 1]
```diff
@@ -34,8 +36,13 @@ export var register = (angular) => {
             AdhTopLevelStateModule.moduleName
         ])
         .config(["adhProcessProvider", (adhProcessProvider : AdhProcess.Provider) => {
-            adhProcessProvider.templates[processType] =
-                "<adh-meinberlin-alexanderplatz-workbench></adh-meinberlin-alexanderplatz-workbench>";
+            adhProcessProvider.templates[processType] = "<adh-meinberlin-alexanderplatz-workbench " +
+                "data-process-options=\"processOptions\"></adh-meinberlin-alexanderplatz-workbench>";
```
Comment (xi) [inline src/meinberlin/meinberlin/static/js/Packages/Meinberlin/Alexanderplatz/Workbench/Module.ts]: This directive does not accept an attribute called `processOptions`.

**Comment by xi** [comment]
`processOption` seems to conflict with the result of options requests to processes (also called `processOptions`). Maybe we can rename the new one to `processProperties`.

File: src/meinberlin/meinberlin/static/js/Packages/Meinberlin/Alexanderplatz/Workbench/Module.ts (hunk 1 above)
Comment (der-john) [inline src/meinberlin/meinberlin/static/js/Packages/Meinberlin/Alexanderplatz/Workbench/Module.ts]: as you said: it works anyways. But I'll add the parameter just in case.
